version: '3.8'

services:
  frontend:
    build: ./
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - frontend-net
    restart: on-failure

networks:
  frontend-net:
    driver: bridge
